// JsFromRoutes CacheKey c1d2425dc68061a297771a3f16756cd2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  getUsersRooms: definePathHelper('get', '/api/choice'),
  create: definePathHelper('post', '/api/message'),
}
