// JsFromRoutes CacheKey d857a9eb7d11eee478c149ebcd0e923a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  getUsersRooms: definePathHelper('get', '/api/choice'),
}
